<a href="https://colab.research.google.com/github/Alex-So-Ma/Fisica_Computacional_2023-1/blob/main/Proyecto_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

def trapezcomp(f, a, b, n):
    """
    integración con regla del trapecio

    Entradas:
    f:  función a integrar
    a:  límite inferior
    b:  límite superior
    n:  división del intervalo
    """

    # Inicio
    h = (b - a) / n
    x = a

    # Regla de composición
    In = f(a)
    for k in range(1, n):
        x  = x + h
        In += 2*f(x)

    return (In + f(b))*h*0.5

def romberg(f, a, b, p):
    """
    integración de Romberg

    Entradas:
    f:  función a integrar
    a:  cota inferior
    b:  cota superior
    p:  filas en la tabla de Romberg
    """

    I = np.zeros((p, p))
    for k in range(0, p):
        # Primeras aproximaciones dada por el método del trapecio
        I[k, 0] = trapezcomp(f, a, b, 2**k)

        # Formula recursiva de Romberg
        for j in range(0, k):
            I[k, j+1] = (4**(j+1) * I[k, j] - I[k-1, j]) / (4**(j+1) - 1)

        print(I[k,0:k+1])   # Muestra los resultados intermedios
    return I

#Ejemplo

p = 5
print('Arreglo teriangular de la integración de Romberg')
I = romberg(np.sin, 0, np.pi/2, p)
solution = I[p-1, p-1]
print('---------------------------------------------------------------')
print('Solución por integración de romberg:',solution)

Ie=1
print('---------------------------------------------------------------')
print('Solución analítica: -cos(pi/2)+cos(0)=', Ie)
print('---------------------------------------------------------------')
print('Arreglo teriangular de los errores porcentuales de la integración de Romberg')
E = np.zeros((p, p))
for k in range(0, p):
  E[k, 0] = np.absolute((I[k,0]-Ie)/Ie)*100

  for j in range(0, k):
    E[k, j+1] = np.absolute((I[k, j+1]-Ie)/Ie)*100

  print(E[k,0:k+1])   # Muestra los errores

Arreglo teriangular de la integración de Romberg
[0.78539816]
[0.94805945 1.00227988]
[0.9871158  1.00013458 0.99999157]
[0.99678517 1.0000083  0.99999988 1.00000001]
[0.99919668 1.00000052 1.         1.         1.        ]
---------------------------------------------------------------
Solución por integración de romberg: 0.9999999999980169
---------------------------------------------------------------
Solución analítica: -cos(pi/2)+cos(0)= 1
---------------------------------------------------------------
Arreglo teriangular de los errores porcentuales de la integración de Romberg
[21.46018366]
[5.1940551  0.22798775]
[1.28841990e+00 1.34584974e-02 8.43452701e-04]
[3.21482811e-01 8.29552397e-04 1.23772714e-05 8.14402035e-07]
[8.03319515e-02 5.16684706e-05 1.90457772e-07 2.98372438e-09
 1.98308037e-10]


In [ ]:
from scipy import integrate

help(integrate.romberg)

Help on function romberg in module scipy.integrate._quadrature:

romberg(function, a, b, args=(), tol=1.48e-08, rtol=1.48e-08, show=False, divmax=10, vec_func=False)
    Romberg integration of a callable function or method.
    
    Returns the integral of `function` (a function of one variable)
    over the interval (`a`, `b`).
    
    If `show` is 1, the triangular array of the intermediate results
    will be printed. If `vec_func` is True (default is False), then
    `function` is assumed to support vector arguments.
    
    Parameters
    ----------
    function : callable
        Function to be integrated.
    a : float
        Lower limit of integration.
    b : float
        Upper limit of integration.
    
    Returns
    -------
    results  : float
        Result of the integration.
    
    Other Parameters
    ----------------
    args : tuple, optional
        Extra arguments to pass to function. Each element of `args` will
        be passed as a single argument to `fun

In [ ]:
from scipy import integrate
import numpy as np

I = integrate.romberg(np.sin, 0, np.pi/2,show=True)
print(I)
print(-np.cos(np.pi/2)+np.cos(0))

Romberg integration of <function vectorize1.<locals>.vfunc at 0x7f7600420af0> from [0, 1.5707963267948966]

 Steps  StepSize   Results
     1  1.570796  0.785398 
     2  0.785398  0.948059  1.002280 
     4  0.392699  0.987116  1.000135  0.999992 
     8  0.196350  0.996785  1.000008  1.000000  1.000000 
    16  0.098175  0.999197  1.000001  1.000000  1.000000  1.000000 

The final result is 0.9999999999980171 after 17 function evaluations.
0.9999999999980171
0.9999999999999999
